server:
  port: ${PORT:5001}  # Valor por defecto si PORT no está configurado
  url: ${SERVER_URL:http://localhost:5001}  # Valor por defecto si SERVER_URL no está configurado

spring:
  profiles:
    default: local

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html # Ruta para acceder a Swagger UI: http://localhost:8085/swagger-ui.html
