server:
  port: ${PORT:5001}
  url: ${SERVER_URL:http://localhost:5001}

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:sqlserver://localhost:1433;databaseName=agro_pacayales;encrypt=true;trustServerCertificate=true}
    username: ${DATABASE_USERNAME:sa}
    password: ${DATABASE_PASSWORD:SqlPassword2026!}
    driver-class-name: ${DATABASE_DRIVER:com.microsoft.sqlserver.jdbc.SQLServerDriver}
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update
    show-sql: false

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
