spring:
  datasource:
   
    url: jdbc:sqlserver://localhost:1433;databaseName=agro_pacayales;encrypt=true;trustServerCertificate=true
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: SqlPassword2026!
  jpa:
   
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: none 
    show-sql: true 